config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  root to: 'pages#home'
  get 'select_category', to: 'posts#select_category'
  get 'show_options', to: 'combinations#show_options'
  
  resources :posts
  resources :combinations
  resources :post_combinations
  resources :categories

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_many :posts

    default_scope -> { order(name: :asc) }
end

app/models/combination.rb
class Combination < ApplicationRecord
    has_many :post_combinations
    has_many :posts, through: :post_combinations
    belongs_to :user
    
    validates :name, presence: true

    default_scope -> { order(created_at: :desc) }
end

app/models/post.rb
class Post < ApplicationRecord
    validates :category_id, presence: true
    validates :picture, presence: true

    belongs_to :user
    belongs_to :category
    has_many :post_combinations
    has_many :combinations, through: :post_combinations
    has_one_attached :picture

    default_scope -> { order(created_at: :desc) }
end

app/models/post_combination.rb
class PostCombination < ApplicationRecord
    belongs_to :post
    belongs_to :combination
    validates :post_id, presence: true
    validates :combination_id, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :combinations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
    posts_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :get_category_by_id, only: [:edit, :update, :destroy]
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.valid?
            @category.save
            redirect_to posts_path
        else
            flash[:error] = "Your category must have a name."
            render 'new'
        end
    end

    def edit
    end

    def update
        if @category.update_attributes(category_params)
            redirect_to posts_path
        else
            render 'edit'
        end
    end

    def destroy
        @category.destroy
        redirect_to posts_path
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def get_category_by_id
        @category = Category.find(params[:id])
    end
end

app/controllers/combinations_controller.rb
class CombinationsController < ApplicationController
    before_action :find_combination, only: [:show, :show_options, :select_posts, :destroy]

    def new
        @combination = current_user.combinations.build
    end

    def create
        @combination = current_user.combinations.build(combination_params)
        if @combination.valid?
            @combination.save
            redirect_to @combination
        else
            flash[:error] = "Your combination must have a name."
            render 'new'
        end
    end

    def show
        @items = @combination.posts.all
    end

    def index
        @combinations = current_user.combinations.all
    end

    def show_options
        @posts = (current_user.posts.all - @combination.posts) | (@combination.posts - current_user.posts.all)
        flash[:notice] = "You don't have any items to add into this combinations." if @posts.empty?
    end

    def destroy
        @combination.destroy
        redirect_to combinations_path
    end

    private

    def combination_params
        params.require(:combination).permit(:name)
    end

    def find_combination
        @combination = params[:combination_id] ? Combination.find(params[:combination_id]) : Combination.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end
end

app/controllers/post_combinations_controller.rb
class PostCombinationsController < ApplicationController
    before_action :find_combination
    
    def new
        PostCombination.create(post_id: params[:post_id], combination_id: params[:combination_id])
        redirect_to @combination
    end

    def destroy
        @post_combination = PostCombination.find_by(post_id: params[:post_id], combination_id: params[:id])
        @post_combination.destroy
        redirect_to @combination
    end

    private
    def find_combination
        @combination = params[:combination_id] ? Combination.find(params[:combination_id]) : Combination.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController  
  before_action :get_post_by_id, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, only: [:new, :edit]
  before_action  :login_user 

  def show
  end

  def index
    @posts = params[:category_id] ? current_user.posts.where("category_id = ?", params[:category_id]) : current_user.posts.all 
    if @posts.empty?
      flash.now[:notice] = "No items in this category."
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.valid?
      @post.save
      maximum_alert
      redirect_to posts_path
    else
      flash[:error] = "Something is wrong. Have you selected a picture and a category?"
      redirect_to new_post_path
    end
  end

  def edit
  end 

  def update
    if @post.update_attributes(posts_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def posts_params
    params.require(:post).permit(:category_id, :picture)
  end

  def get_post_by_id
    @post = Post.find(params[:id])
  end

  def get_categories
    @categories = Category.all.map{ |cat| [cat.name, cat.id] }
  end

  def maximum_alert
    [45, 50, 55, 60, 65, 70].each do |limit|
      flash[:pop_up] = "too many clothes!!!" if current_user.posts.count == limit
    end    
  end

  def login_user
    unless user_signed_in?
      redirect_to login_path
      flash[:error] = "You must login first."
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :current_password)
  end
end

app/helpers/application_helper.rb
require "navigation_helper.rb"

module ApplicationHelper
  include NavigationHelper

  def get_category_count(category)
    Category.find_by(name: category.name).posts.where("user_id = ?", current_user.id).count
  end

  def render_sidebar
    return true unless !user_signed_in? || current_page?(root_path)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/combinations_helper.rb
module CombinationsHelper
    def display_text(combinations)
        combinations.empty? ? "You don't have any looks yet." : "Your looks:" 
    end    
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      "layouts/navigation/signed_in_links"
    else
      "layouts/navigation/non_signed_in_links"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_combinations_helper.rb
module PostCombinationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_category_name(cat_id = nil)
    cat_id ? Category.find(cat_id).name : "All clothes"
  end
end

app/views/categories/edit.html.erb
<div class="col-sm-6 col-sm-offset-3 mt-5 mx-auto">
    <h2 class="text-center title-medium mt-5 mb-5">Edit category</h2>
    <%= bootstrap_form_for @category do |f| %>
        <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>

        <%= f.text_field :name, placeholder: "name", class: 'pl-2' %>

        <%= f.submit 'Save', class: 'btn sign-up-button btn-outline-secondary w-100 mt-3' %>
    <% end %>
    <br/>
    <%= link_to "Back", posts_path, class:"btn btn-outline-secondary" %>
</div>

app/views/categories/new.html.erb
<div class="col-sm-6 col-sm-offset-3 mt-5 mx-auto">
    <h2 class="text-center title-medium mt-5 mb-5">Create a new category</h2>
    <%= bootstrap_form_for @category do |f| %>
        <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>

        <%= f.text_field :name, placeholder: "name", class: 'pl-2' %>

        <%= f.submit 'Create', class: 'btn sign-up-button btn-outline-secondary w-100 mt-3' %>
    <% end %>
    <br/>
    <%= link_to "Back", posts_path, class:"btn btn-outline-secondary" %>
</div>

app/views/combinations/index.html.erb
<div class="col pt-3">
    <h1 class="title-small mt-1 mb-4 ml-4">
        <%= display_text(@combinations) %>
    </h1>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice", :class => "ml-5 mt-3" ) if flash[:notice] %>
    <ul id="combinations-list" class="mt-4 pl-3">
        <% @combinations.each do |combination| %>
            <li class="mx-2 mb-2 border border-secondary rounded p-1">
                <%= link_to combination, class:"paragraph-big combination-title p-3" do %>
                    <%= combination.name %>
                    <ul id='combination-container' class='pt-2 pl-1'>
                        <% combination.posts.each do |item| %>
                            <li class="ml-1">
                                <div class='image-small' style='background-image: url(<%=(url_for(item.picture)) %>)'></div>
                            </li>
                        <% end %>
                    </ul>
                <% end %>
            </li>   
        <% end %>
    </ul>
    <%= link_to new_combination_path, class:"btn btn-outline-secondary ml-4 mt-2 mt-sm-4 mb-3" do %>
        Create new look
        <i class="fas fa-plus-circle"></i>
    <% end %>
    <br/>
    <%= link_to "Back", posts_path, class:"btn btn-outline-secondary ml-4" %>
</div>

app/views/combinations/new.html.erb
<div class="col-sm-6 col-sm-offset-3 mt-5 mx-auto">
    <h2 class="text-center title-medium mt-5 mb-5">Create a new look</h2>
    <%= bootstrap_form_for @combination do |f| %>
        <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>

        <%= f.text_field :name, placeholder: "name", class: 'pl-2' %>

        <%= f.submit 'Next', class: 'btn sign-up-button btn-outline-secondary w-100 mt-3' %>
    <% end %>
    <%= link_to "Back", combinations_path, class:"btn btn-outline-secondary text-body ml-sm-4 ml-1 mt-4" %>
</div>

app/views/combinations/show.html.erb
<div class="col pt-3">
    <h1 class="title-small mt-1 mb-4 ml-4"><%= @combination.name %></h1>
    <% if @items.empty? %>
        <h1 class="paragraph-big">No items in this combination yet</h1>
    <% else %>
        <ul id="images-container" class="p-0 mt-1">
            <% @items.each do |item| %>
                <li class="mx-1 mx-sm-4">
                    <div style='background-image: url(<%=(url_for(item.picture)) %>)'>
                        <%= link_to post_combination_path(:combination_id => @combination_id, :post_id => item.id), method: :delete,  class:"btn btn-secondary ml-2",  data: { confirm: 'Are you sure?' } do %>
                            <i class="far fa-trash-alt"></i>
                        <% end %>
                    </div>
                </li>
            <% end %>
        </ul>
    <% end %>
    <%= link_to show_options_path(:combination_id => @combination.id), class:"btn btn-outline-secondary ml-4 mt-4 mb-3" do %>
        Add items
        <i class="fas fa-plus-circle"></i>
    <% end %>
    <%= link_to "Delete look", combination_path(@combination), method: :delete,  class:"btn btn-outline-secondary ml-4 mt-4 mb-3",  data: { confirm: 'Are you sure?' } %>
    <br/>
   <%= link_to "Back", combinations_path, class:"btn btn-outline-secondary ml-4" %> 
</div>
  

app/views/combinations/show_options.html.erb
<div class="col pt-3">
    <h1 class="paragraph-big mt-3 mb-4 ml-4">
        Select the items you want to add in your combination:
    </h1>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice", :class => "ml-5 mt-3" ) if flash[:notice] %>
    <ul id="images-container" class="p-0 mt-1">
        <% @posts.each do |post| %>
            <li class="mx-1 mx-sm-4">
                <div style='background-image: url(<%=(url_for(post.picture)) %>)'>
                    <%= link_to new_post_combination_path(:combination_id => params[:combination_id], :post_id => post.id), class:"btn btn-secondary ml-2" do %>
                        <i class="fas fa-plus-circle"></i>
                    <% end %>
                </div>
            </li>
        <% end %>
    </ul>
    <%= link_to "Back", combinations_path, class:"btn btn-outline-secondary ml-sm-4 ml-1 mt-4 mb-2" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capsule Wardrobe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta property='og:image' content='https://agile-sea-56583.herokuapp.com/assets/CW-home.png'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation/navigation' %>
    <%= render 'layouts/navigation/sidebar_mobile' if render_sidebar %>
    <div class="container-fluid full-page">
      <div class="row full-page" id="body-row">
        <%= render 'layouts/navigation/sidebar' if render_sidebar %>
        
        <%= yield %>
      </div>
    </div>
    

    <nav class="navbar-bottom navbar py-0">
      <span class="navbar-text">
        Created by Bruna Genz
      </span>
    </nav>
  </body>
</html>

app/views/layouts/navigation/_navigation.html.erb
<nav class="top-navbar navbar fixed-top d-flex justify-content-between">
  <%= link_to 'Capsule Wardrobe', root_path, class: 'navbar-brand white-link ml-3' %>
  <ul class="navbar-nav">
    <%= render collapsible_links_partial_path %>
  </ul>
</nav>

app/views/layouts/navigation/_non_signed_in_links.html.erb
<li class="nav-item">
    <%= link_to 'Log in', login_path, class: 'nav-link white-link mr-3' %>
</li>

app/views/layouts/navigation/_sidebar.html.erb
<div class="sidebar-sticky border-right border-secondary p-1">
    <ul class="nav flex-column border-bottom border-secondary">
        <li class="nav-item d-flex justify-content-center py-3 px-5">
            <h1 class="title-small">
                <%= link_to posts_path, class:'name-link' do %>
                    <% current_user.name %>
                <% end %>
            </h1>
        </li>
    </ul>
    <ul class="nav flex-column">
        <li class="nav-item big d-flex justify-content-center pt-2">
            <p class="nav-link mb-0" href="#">
                Categories
            </p>
        </li>
        <li class="nav-item d-flex justify-content-center">
            <%= link_to posts_path, class: 'nav-link' do %>
                All
                <span class="badge badge-secondary ml-1">
                    <%= current_user.posts.count %>
                </span>
            <% end %>
        <li>
        <% Category.all.each do |category| %>
            <li class="nav-item d-flex justify-content-center">
                <%= link_to posts_path(:category_id => category.id), class: 'nav-link' do %>
                    <%= category.name %>
                    <span class="badge badge-secondary ml-1">
                        <%= get_category_count(category) %>
                    </span>
                <% end %>
            </li>
        <% end %>
        <li class="nav-item d-flex justify-content-center">
            <%= link_to 'Add category', new_category_path, class: 'nav-link' %>
        </li>
    </ul>
    <ul class="nav flex-column border-top border-secondary">
        <li class="nav-item big d-flex justify-content-center pt-2">
            <p class="nav-link mb-0" href="#">
                My looks
            </p>
        </li>
        <li class="nav-item d-flex justify-content-center">
            <%= link_to combinations_path, class:"nav-link" do %>
                All
                <span class="badge badge-secondary ml-1">
                    <%= current_user.combinations.count %>
                </span>
            <% end %>
        </li>
    </ul>
    <ul class="nav flex-column border-top border-secondary">
        <li class="nav-item big d-flex justify-content-center pt-2">
            <%= link_to new_post_path, class:"nav-link" do %>
                Add clothes
                <i class="fas fa-plus-circle"></i>
            <% end %>
        </li>
    </ul>
</div>

app/views/layouts/navigation/_sidebar_mobile.html.erb
<div class="sidebar-sticky sidebar-mobile border-bottom border-secondary pt-4 pb-2 mb-2">
    <ul class="nav flex-column ml-3">
        <li class="nav-item d-flex justify-content-center ml-3 mr-2">
            <h1 class="title-small">
                <%= link_to posts_path, class:'name-link' do %>
                    <% current_user.name %>
                <% end %>
            </h1>
        </li>
    </ul>
    <div class="dropdown">
        <button type="button" class="btn dropdown-toggle white-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
        </button>
        <div class="dropdown-menu dropdown-menu-right scrollable-menu">
            <%= link_to posts_path, class: 'nav-link' do %>
                All
                <span class="badge badge-secondary ml-1">
                    <%= current_user.posts.count %>
                </span>
            <% end %>

            <% Category.all.each do |category| %>
                <%= link_to posts_path(:category_id => category.id), class: 'nav-link' do %>
                    <%= category.name %>
                    <span class="badge badge-secondary ml-1">
                        <%= get_category_count(category) %>
                    </span>
                <% end %>
            <% end %>

            <div class="dropdown-divider"></div>
            <%= link_to 'Add category', new_category_path, class: 'nav-link' %>

            <div class="dropdown-divider"></div>
            <%= link_to combinations_path, class:"nav-link" do %>
                My looks
                <span class="badge badge-secondary ml-1">
                    <%= current_user.combinations.count %>
                </span>
            <% end %>
        </div>
    </div>

    <ul class="nav flex-column mr-3">
        <li class="nav-item d-flex justify-content-center pt-2">
            <%= link_to new_post_path, class:"btn btn-secondary btn-sm text-white" do %>
                Add clothes
            <% end %>
        </li>
    </ul>
</div>

app/views/layouts/navigation/_signed_in_links.html.erb
<div class="btn-group align-items-center">
    <div class="dropdown">
        <button type="button" class="btn dropdown-toggle white-link mr-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Options
        </button>
        <div class="dropdown-menu dropdown-menu-right">
            <%= link_to "My wardrobe", posts_path, class: 'dropdown-item' %>
            <%= link_to "Add clothes", new_post_path, class: 'dropdown-item' %>
            <%= link_to "Edit profile", edit_user_registration_path, class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="col-sm-6 col-sm-offset-3 mt-5 mx-auto">
    <h2 class="text-center title-medium mt-5 mb-5">Edit item</h2>
    <%= bootstrap_form_for @post do |f| %>
        <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>

        <%= f.file_field :picture,  
                        class: 'form-control' %>

        <%= f.select(:category_id, options_for_select(@categories), :prompt => "Select one!") %>

        <%= link_to '(add category)', new_category_path, class: 'nav-link absolute-link' %>

        <%= f.submit 'Edit item', class: 'btn sign-up-button btn-outline-secondary w-100 mt-3' %>
    <% end %>
    <br/>
    <%= link_to "Back", posts_path, class:"btn btn-outline-secondary" %>
</div>

app/views/posts/index.html.erb
<div class="col pt-3">
    <div class="d-flex align-items-center">
        <h1 class="title-small mt-2 ml-sm-5 ml-2 mr-3">
            <%= get_category_name(params[:category_id]) %>
        </h1>
    
    <% if params[:category_id] %>
      <%= link_to edit_category_path(params[:category_id]), class: 'simple-link mr-2 pt-1' do %>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to category_path(params[:category_id]), class: 'simple-link pt-1', method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    <% end %>

    </div>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice", :class => "ml-5 mt-3" ) if flash[:notice] %>
    
    <% if flash[:pop_up] %>
        <div class="alert alert-warning alert-dismissible fade show mx-5 mt-3" role="alert">
            <strong>So many clothes!</strong> <br/>
            <p>Although the limit for the number of items you have in your wardrobe doesn't 
            need to be so rigid, the main goal of making a capsule is to declutter and keeping 
            only pieces that are useful and important for you.</p>
            <p>This is a good time to re-evaluate what you have in your wardrobe. Remember 
            that you can always edit your capsule, make new looks, remove pieces that don't
                make sense anymore. </p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
    
    <ul id="images-container" class="p-0 mt-1">
        <% @posts.each do |post| %>
            <li class="mx-1 mx-sm-4">
                <div style='background-image: url(<%= cloudinary_url(post.picture.key) %>)'>
                    <span id="left-links" class="ml-2">
                        <%= link_to edit_post_path(post), class:"btn btn-secondary" do %>
                            <i class="fas fa-edit"></i>
                        <% end %>
                        <%= link_to post_path(post), method: :delete, class:"btn btn-secondary ml-sm-1",  data: { confirm: 'Are you sure?' } do %>
                            <i class="far fa-trash-alt"></i>
                        <% end %>
                    </span>
                    <span id="right-links">
                        <%= link_to post, class:"btn btn-secondary mr-2" do %>
                            <i class="fas fa-expand"></i>
                        <% end %>
                    </span>
                </div>
            </li>
        <% end %>
    </ul>
</div>

app/views/posts/new.html.erb
<div class="col-sm-6 col-sm-offset-3 mt-5 mx-auto">
    <h2 class="text-center title-medium mt-5 mb-5">Add clothes</h2>
    <%= bootstrap_form_for @post do |f| %>
        <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>

        <%= f.file_field :picture,  
                        class: 'form-control',
                        direct_upload: true  %>

        <%= f.select(:category_id, options_for_select(@categories), :prompt => "Select one!") %>

        <%= link_to '(add category)', new_category_path, class: 'nav-link absolute-link' %>

        <%= f.submit 'Create', class: 'btn sign-up-button btn-outline-secondary w-100 mt-3' %>
    <% end %>
    <br/>
    <%= link_to "Back", posts_path, class:"btn btn-outline-secondary" %>
</div>

app/views/posts/show.html.erb
<div id="image-expand" class="mx-auto mt-sm-5 mt-4 justify-content-end" style='background-image: url(<%=(url_for(@post.picture)) %>)'>
    <%= link_to posts_path, class:"btn btn-secondary btn-sm mr-3" do %>
        <i class="fas fa-compress"></i>
    <% end %>
</div>